server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home-order
  flyway:
    enabled: true
    baseline-on-migrate: false

logging:
  level:
    org.jetbrains.exposed.sql: DEBUG

springdoc:
  swagger-ui:
    path: /api/docs
    tags-sorter: alpha
    operations-sorter: alpha